# Generated by Django 5.2 on 2025-06-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivana', '0002_emailotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.JSONField()),
                ('quantity', models.IntegerField()),
                ('total_price', models.IntegerField()),
            ],
        ),
    ]
