# Generated by Django 5.2 on 2025-06-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivana', '0003_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='username',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
