# Generated by Django 5.2 on 2025-06-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivana', '0006_drive'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='accepted_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
