# Generated by Django 5.2 on 2025-06-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivana', '0008_ride'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.JSONField()),
            ],
        ),
    ]
